### ISSUE TITLE
For svg to pdf converter processor librsvg  is not working for API

### ISSUE THREAD

**Issue by habiburrahman0540** [smidyo/vectorexpress-api#1]
Hi, For svg to pdf converter processor librsvg  is not working for API.
I am trying to get svg to pdf to using this api and converter , i also got status code 200 but pdf file does not generate by this API : https://vector.express/api/v2/public/convert/svg/librsvg/pdf/

**Comment by FrankSandqvist** [comment]
Hi Habi,

Apologies for the late response - were you able to fix this issue?
