### ISSUE TITLE
Detect non-vector images?

### ISSUE THREAD

**Issue by Wackytoaster** [smidyo/vectorexpress-api#11]
Is there a way to detect if a file contains non-vector images? Many vector files can contain embedded image files and I'd like to analyze them so that I can reject files with embedded images.

Cheers!

**Comment by FrankSandqvist** [comment]
Hey @Wackytoaster! 

We do not, at the moment, support any dedicated analyze endpoint for detecting raster images in a file.

However, one thing you can try, is to first convert your vector file into SVG and subsequently doing a search for the <image /> tag in the SVG contents.

**Comment by Wackytoaster** [comment]
That could work. Thanks for the idea!
