### ISSUE TITLE
Error "An error occurred during conversion" when using SVGO

### ISSUE THREAD

**Issue by lkaisers** [smidyo/vectorexpress-api#6]
Hi,

we want to use the Vector Express API to optimize our SVG files being uploaded to WordPress. I use wp_remote_post and curl_file_create to POST everything to the API. But everytime there's an error like:
```
[message] => An error occurred during conversion
[chainId] => f2853966-01a4-4f7e-9e79-e14c7bdc9855
[program] => svgo
[inputFormat] => svg
[outputFormat] => svg
```

The same error occurs when I use curl via the command line.
What I'm unsure about is whether I need to pass the parameters or if they are optional.

**Comment by FrankSandqvist** [comment]
Hi @lkaisers,

Sorry to hear you're having issues. Could you post some code snippets from your PHP and/or CURL? I could have a look.

Best,
Frank
