### ISSUE TITLE
Purchased pay as you go but got nothing

### ISSUE THREAD

**Issue by simonbarker** [smidyo/vectorexpress-api#8]
Hi,

I purchased a pay as you go plan through vector.express and received no account information or API key. I've emailed the sales email address but had no reply.

Is this project legit and active?

**Comment by FrankSandqvist** [comment]
Hey @simonbarker,

Sorry to hear that! Looking into it right now. There may be a delay until you receive the access token after signing up.

**Comment by simonbarker** [comment]
Thanks @FrankSandqvist it's been about 48 hours since purchase so possibly something has gone wrong in somewhere 😕

**Comment by FrankSandqvist** [comment]
@simonbarker I'll get back to you over email!

**Comment by chans97** [comment]
Actually, I'm having the same problem. I paid with my card, but the next page doesn't show up (I didn't even log in). Where can I sign up for membership?) Please help me.   papajuju123@naver.com

**Comment by FrankSandqvist** [comment]
Hi @chans97 -- sorry to hear this. We are looking into it right now, and will get back to you asap! @corrideat
